import type { PublicLocale } from '@/lib/business-config';
type Pair=Record<PublicLocale,string>; type Legal={title:Pair;description:Pair;sections:ReadonlyArray<{title:Pair;body:Pair}>};
export const legalContent={
  'privacy-policy':{title:{ar:'سياسة الخصوصية',en:'Privacy Policy'},description:{ar:'معلومات عامة عن معالجة بيانات طلبات المشاريع والتواصل.',en:'General information about handling project enquiry and contact data.'},sections:[{title:{ar:'البيانات التي ترسلها',en:'Information you submit'},body:{ar:'قد نعالج الاسم وبيانات التواصل والشركة ومتطلبات المشروع التي ترسلها طوعاً عبر النموذج، لغرض الرد على طلبك وإدارة التواصل المتعلق به.',en:'We may process the name, contact details, company, and project requirements you voluntarily submit, to respond to and manage your enquiry.'}},{title:{ar:'الحفظ والمشاركة',en:'Storage and sharing'},body:{ar:'تُحفظ الطلبات في نظام الموقع المحمي. لا ينبغي مشاركة البيانات مع طرف آخر إلا عند الحاجة لتقديم الخدمة أو الالتزام النظامي وبضوابط مناسبة.',en:'Enquiries are stored in the protected website system. Information should only be shared when needed to deliver the service or meet a legal obligation, with appropriate safeguards.'}},{title:{ar:'طلبات الخصوصية',en:'Privacy requests'},body:{ar:'يمكن استخدام بريد الشركة المنشور لطلب الوصول أو التصحيح أو الحذف. يعتمد التعامل مع الطلب على الأنظمة والالتزامات المعمول بها.',en:'You may use the published company email to request access, correction, or deletion. Handling depends on applicable laws and obligations.'}}]},
  'terms-and-conditions':{title:{ar:'الشروط والأحكام',en:'Terms and Conditions'},description:{ar:'شروط عامة لاستخدام الموقع وبدء مناقشات المشاريع.',en:'General terms for website use and initial project discussions.'},sections:[{title:{ar:'محتوى الموقع',en:'Website content'},body:{ar:'المعلومات المنشورة تعريفية ولا تمثل عرضاً ملزماً. يتحدد نطاق كل مشروع ومراحله وتكلفته في اتفاق مكتوب مستقل.',en:'Published information is introductory and is not a binding offer. Each project’s scope, milestones, and price are defined in a separate written agreement.'}},{title:{ar:'الاستخدام المقبول',en:'Acceptable use'},body:{ar:'يجب عدم إساءة استخدام النماذج أو محاولة الوصول غير المصرح به أو إرسال محتوى ضار أو غير نظامي.',en:'Forms must not be abused, and users must not attempt unauthorized access or submit harmful or unlawful content.'}},{title:{ar:'الملكية والحقوق',en:'Ownership and rights'},body:{ar:'حقوق المخرجات والبرمجيات والمواد الخاصة بكل مشروع تُحدد في عقد المشروع، ولا يُفترض انتقالها من خلال استخدام هذا الموقع.',en:'Rights in project deliverables, software, and materials are defined in the project agreement and are not transferred by using this website.'}}]},
  'cookie-policy':{title:{ar:'سياسة ملفات الارتباط',en:'Cookie Policy'},description:{ar:'معلومات عن التخزين الضروري وتشغيل الموقع.',en:'Information about essential storage and website operation.'},sections:[{title:{ar:'الاستخدام الحالي',en:'Current use'},body:{ar:'قد يستخدم الموقع ملفات ارتباط ضرورية للجلسات الآمنة وتسجيل دخول الإدارة وتفضيلات التشغيل. لا ينبغي إضافة تحليلات أو إعلانات غير ضرورية قبل توثيقها والحصول على الموافقة اللازمة.',en:'The site may use storage essential for secure sessions, admin authentication, and operational preferences. Non-essential analytics or advertising should not be introduced until documented and appropriate consent is implemented.'}},{title:{ar:'التحكم',en:'Control'},body:{ar:'يمكن ضبط ملفات الارتباط من إعدادات المتصفح، لكن تعطيل الضرورية قد يمنع بعض الوظائف الآمنة.',en:'Cookies can be controlled through browser settings, but disabling essential storage may prevent secure functionality.'}}]},
  'refund-cancellation-policy':{title:{ar:'سياسة الإلغاء والاسترداد',en:'Refund and Cancellation Policy'},description:{ar:'مبادئ عامة؛ ويظل عقد المشروع المرجع الملزم.',en:'General principles; the signed project agreement remains controlling.'},sections:[{title:{ar:'المشاريع المخصصة',en:'Custom projects'},body:{ar:'لأن العمل الرقمي المخصص يُنفذ على مراحل، تحدد شروط الإلغاء والاسترداد في عرض السعر والعقد بحسب الأعمال المنجزة والتكاليف الملتزم بها.',en:'Because custom digital work is delivered in stages, cancellation and refund terms are defined in the quotation and contract according to completed work and committed costs.'}},{title:{ar:'طلب الإلغاء',en:'Cancellation request'},body:{ar:'يجب تقديم الطلب عبر قناة التواصل المعتمدة مع رقم المشروع. لا يضمن إرسال الطلب استرداداً حتى تتم مراجعة الاتفاق وحالة التنفيذ.',en:'Requests should be made through the agreed contact channel with the project reference. Submitting a request does not guarantee a refund until the agreement and delivery status are reviewed.'}}]},
} as const satisfies Record<string,Legal>;
export type LegalSlug=keyof typeof legalContent;
