import type { PublicLocale } from '@/lib/business-config';

type Pair = Record<PublicLocale, string>;
export type SeoLanding = { slug: string; title: Pair; description: Pair; intro: Pair; sections: Array<{ title: Pair; text: Pair }>; faq: Array<{ q: Pair; a: Pair }>; serviceSlug: string; areas: readonly string[] };

const commonFaq = (serviceAr:string,serviceEn:string) => [{ q:{ar:`كيف يبدأ مشروع ${serviceAr}؟`,en:`How does a ${serviceEn} project begin?`}, a:{ar:'نبدأ بجلسة اكتشاف لفهم الهدف والمستخدمين والمحتوى والتكاملات، ثم نحدد نطاقاً ومراحل قابلة للمراجعة.',en:'We begin with discovery to understand goals, users, content, and integrations, then define a reviewable scope and milestones.'} },{ q:{ar:'هل يشمل التنفيذ العربية والإنجليزية؟',en:'Can delivery include Arabic and English?'},a:{ar:'نعم عند طلب ذلك في النطاق، مع تصميم RTL ومراجعة التنقل والنماذج والبيانات الوصفية لكل لغة.',en:'Yes when included in scope, with RTL design and review of navigation, forms, and metadata for each language.'} }];
const item=(slug:string,titleAr:string,titleEn:string,descAr:string,descEn:string,serviceSlug:string,focusAr:string,focusEn:string):SeoLanding=>({slug,title:{ar:titleAr,en:titleEn},description:{ar:descAr,en:descEn},intro:{ar:`نساعد الأعمال في السعودية على تخطيط وتنفيذ ${focusAr} يركز على وضوح الخدمة وسهولة الاستخدام والأداء. نعمل عن بُعد مع فرق في مدن المملكة دون الادعاء بوجود مكاتب محلية فيها.`,en:`We help Saudi businesses plan and deliver ${focusEn} focused on service clarity, usability, and performance. We work remotely with teams across the Kingdom without implying physical offices in those cities.`},sections:[{title:{ar:'ما الذي يشمله العمل',en:'What the work covers'},text:{ar:'اكتشاف المتطلبات، وهندسة المحتوى، وتصميم الواجهات، والتطوير، والاختبار، وتهيئة الإطلاق والقياس وفق نطاق المشروع.',en:'Requirements discovery, content architecture, interface design, development, testing, and launch preparation according to the agreed scope.'}},{title:{ar:'تنفيذ مناسب للسوق السعودي',en:'Delivery suited to the Saudi market'},text:{ar:'نراعي التجربة العربية وRTL والأجهزة المحمولة ومتطلبات التكامل المحلية عند الحاجة، ولا نربط أي مزود دفع أو خدمة قبل التحقق من ملاءمته للمشروع.',en:'We account for Arabic, RTL, mobile use, and relevant local integrations. No payment or service provider is committed before confirming project fit.'}},{title:{ar:'أداء قابل للقياس',en:'Measurable delivery'},text:{ar:'نحدد مؤشرات مناسبة مثل سرعة الصفحات وإتمام النماذج وجودة البحث، ثم نختبرها قبل الإطلاق بدلاً من تقديم وعود غير قابلة للتحقق.',en:'We define suitable indicators such as page speed, form completion, and search quality, then test them before launch instead of making unverifiable promises.'}}],faq:commonFaq(focusAr,focusEn),serviceSlug,areas:['Riyadh','Jeddah','Dammam','Khobar']});

export const seoLandings = [
  item('web-development-company-riyadh','شركة تطوير مواقع في الرياض','Web Development Company in Riyadh','تصميم وتطوير مواقع عربية وإنجليزية سريعة للأعمال التي تخدم عملاء الرياض.','Arabic and English website strategy, design, and development for businesses serving Riyadh.','web','موقع أعمال احترافي','a professional business website'),
  item('website-development-saudi-arabia','تطوير مواقع في السعودية','Website Development in Saudi Arabia','تطوير مواقع أعمال متجاوبة وثنائية اللغة للشركات في المملكة.','Responsive bilingual business website development for organizations across Saudi Arabia.','web','موقع متجاوب قابل للتطوير','a scalable responsive website'),
  item('mobile-app-development-saudi-arabia','تطوير تطبيقات الجوال في السعودية','Mobile App Development Saudi Arabia','تخطيط وتصميم وتطوير تطبيقات جوال للأعمال والمستخدمين في السعودية.','Mobile product planning, UX, and development for Saudi businesses and users.','app','تطبيق جوال عملي','a practical mobile application'),
  item('ecommerce-development-riyadh','تطوير المتاجر الإلكترونية في الرياض','E-commerce Development Riyadh','متاجر عربية سريعة مع تجربة شراء واضحة وتكاملات يتم اختيارها حسب المتطلبات.','Arabic-first stores with clear purchase journeys and integrations selected for actual requirements.','ecommerce','متجر إلكتروني عربي','an Arabic-first e-commerce store'),
  item('arabic-website-development','تطوير المواقع العربية','Arabic Website Development','مواقع RTL عربية مصممة للمحتوى والتنقل والنماذج ومحركات البحث.','Arabic RTL websites designed around content, navigation, forms, and search visibility.','web','تجربة ويب عربية متقنة','a considered Arabic web experience'),
  item('ai-automation-company-saudi-arabia','شركة أتمتة وذكاء اصطناعي في السعودية','AI Automation Company Saudi Arabia','أتمتة مدروسة للعمليات المتكررة مع ضوابط وقياس ومراجعة بشرية.','Considered automation for repeatable workflows with controls, measurement, and human review.','ai','حل أتمتة مسؤول','a responsible automation solution'),
  item('pos-software-development-saudi-arabia','تطوير أنظمة نقاط البيع في السعودية','POS Software Development Saudi Arabia','تحليل وتطوير أنظمة نقاط بيع وعمليات مترابطة حسب احتياجات النشاط.','Analysis and development of POS and connected operational systems based on business needs.','software','نظام نقاط بيع مخصص','a custom POS system'),
] as const satisfies readonly SeoLanding[];

export function getSeoLanding(slug:string){return seoLandings.find(item=>item.slug===slug)}
