import type { PublicLocale } from '@/lib/business-config';
type Pair = Record<PublicLocale, string>;
const pair = (ar: string, en: string): Pair => ({ ar, en });
export type SupportPackage = { id: string; name: Pair; summary: Pair; included: readonly Pair[]; support: Pair; response: Pair; monitoring: Pair; backups: Pair; exclusions: readonly Pair[]; featured?: boolean };

export const supportPackages: readonly SupportPackage[] = [
  { id: 'essential', name: pair('العناية الأساسية', 'Essential Care'), summary: pair('للمواقع المستقرة التي تحتاج صيانة دورية وقناة واضحة لطلبات الدعم.', 'For stable websites needing routine maintenance and a clear support-request channel.'), included: [pair('تحديثات دورية للتبعيات بعد الاختبار', 'Tested routine dependency updates'), pair('معالجة الأعطال ضمن النطاق المتفق', 'Defect investigation within agreed scope'), pair('مراجعة أساسية للصحة والأمان', 'Baseline health and security review')], support: pair('طلبات دعم مكتوبة عبر القناة المتفق عليها.', 'Written support requests through the agreed channel.'), response: pair('فرز الطلب وتأكيد الأولوية والخطوة التالية وفق الأثر والتوافر، دون وعد بزمن ثابت غير متفق عليه.', 'Triage, priority confirmation, and next-step guidance based on impact and availability, without an uncontracted fixed response promise.'), monitoring: pair('فحوصات دورية متفق عليها؛ لا تشمل مراقبة مستمرة ما لم تُضف إلى النطاق.', 'Agreed periodic checks; continuous monitoring is not included unless added to scope.'), backups: pair('مراجعة إعدادات النسخ الاحتياطي عندما تدعمها منصة الاستضافة؛ الاستعادة تُختبر فقط إذا شملها النطاق.', 'Review of hosting-supported backup settings; restore testing only when included in scope.'), exclusions: [pair('تطوير ميزات جديدة', 'New feature development'), pair('خدمات أو تراخيص الطرف الثالث', 'Third-party services or licences'), pair('دعم البنية غير الموثقة', 'Unsupported undocumented infrastructure')] },
  { id: 'growth', name: pair('دعم النمو', 'Growth Support'), summary: pair('للفرق التي تطور المحتوى وتجربة المستخدم وتحتاج دورة تحسين منتظمة.', 'For teams evolving content and user experience through a regular improvement cycle.'), included: [pair('كل عناصر العناية الأساسية', 'Everything in Essential Care'), pair('سعة شهرية متفق عليها للتحسينات الصغيرة', 'Agreed monthly capacity for small improvements'), pair('مراجعة أداء وتجربة دورية', 'Periodic performance and experience review'), pair('دعم تحديث المحتوى والصفحات', 'Content and page-update support')], support: pair('قناة دعم منظمة مع مراجعة دورية للأولويات.', 'Structured support channel with recurring priority review.'), response: pair('تصنيف الطلبات حسب أثرها وإدراجها في السعة المتفق عليها أو تقديم تقدير منفصل.', 'Requests are classified by impact and scheduled into agreed capacity or estimated separately.'), monitoring: pair('مراقبة وفحوصات حسب الأدوات المعتمدة في العرض النهائي.', 'Monitoring and checks according to tools approved in the final proposal.'), backups: pair('متابعة نجاح النسخ المتاح من المزود واختبارات استعادة دورية إذا تم التعاقد عليها.', 'Review of provider-supported backup status and periodic restore tests when contracted.'), exclusions: [pair('إعادة تصميم شاملة أو بناء منتج جديد', 'Full redesigns or new product builds'), pair('حملات التسويق وإدارة الإعلانات', 'Marketing campaigns and ad management'), pair('ضمانات مزودي الاستضافة والخدمات الخارجية', 'Guarantees for hosting or external providers')], featured: true },
  { id: 'critical', name: pair('الأعمال الحرجة', 'Business Critical'), summary: pair('للأنظمة المهمة التي تحتاج نطاق دعم وتشغيل ومخاطر مصمماً خصيصاً قبل التعاقد.', 'For important systems requiring a tailored support, operations, and risk scope before engagement.'), included: [pair('خطة تشغيل وتصعيد مخصصة', 'Tailored operating and escalation plan'), pair('مراجعات أمان وأداء أعمق حسب النظام', 'Deeper system-specific security and performance reviews'), pair('تخطيط الاستمرارية والاستعادة', 'Continuity and recovery planning'), pair('سعة تحسين ودعم يتم تحديدها تعاقدياً', 'Contractually defined improvement and support capacity')], support: pair('قنوات وأدوار تصعيد تُوثق في اتفاق الدعم.', 'Support channels and escalation roles documented in the support agreement.'), response: pair('منهج الاستجابة والأولويات والتغطية يُحدد بعد تقييم النظام؛ لا تُعرض هنا اتفاقية مستوى خدمة غير موثقة.', 'Response approach, priorities, and coverage are defined after system assessment; no unsupported SLA is advertised here.'), monitoring: pair('مراقبة وتنبيهات مصممة حسب المكونات الحرجة والبيئة المتاحة.', 'Monitoring and alerting designed around critical components and the available environment.'), backups: pair('سياسة نسخ واستعادة واختبار تُصمم حسب مزود الاستضافة وتصنيف البيانات.', 'Backup, recovery, and testing policy designed around hosting provider and data classification.'), exclusions: [pair('الأنظمة غير القابلة للوصول أو غير الموثقة قبل التقييم', 'Inaccessible or undocumented systems before assessment'), pair('الحوادث الناتجة عن مزود خارجي خارج نطاق التحكم', 'External-provider incidents outside direct control'), pair('أي التزام غير منصوص عليه في اتفاق الدعم', 'Any commitment not stated in the support agreement')] },
];
